### ISSUE TITLE
SHA verification issue since 0.2.0 release

### ISSUE THREAD

**Issue by mouglou** [dmachard/terraform-provider-http-client#4]
Hi,

One of our pipeline is using your tool, and since the release of the 0.2.0 version, we have this issue.

│ Error: Failed to install provider
│ 
│ Error while installing dmachard/http-client v0.2.0: checksum list has
│ unexpected SHA-256 hash
│ 7b1c2ca87c9b7ce8ddfb2e0ca1bea36cda24331fbdb39701680832f3e1efef60 (expected
│ 6b903d2c1e2b0bc1bc083cb829329a6a04e3966dfa17288ed151a98a9be7263b)

I will try to force the old 0.1.0 version, but I think something wrong with checksum of the new version.

Not sure what I can do on my side.

Thanks !

**Comment by dmachard** [comment]
7b1c2ca87c9b7ce8ddfb2e0ca1bea36cda24331fbdb39701680832f3e1efef60 is the good one
Can you try the new release 0.0.3 ?

**Comment by mouglou** [comment]
> 7b1c2ca87c9b7ce8ddfb2e0ca1bea36cda24331fbdb39701680832f3e1efef60 is the good one Can you try the new release 0.3.0 ?

Hi @dmachard !
Yes, we just re-run our pipeline, and as we don't fix the version on your provider, it download the latest one.
And so with the 0.3.0 version, we don't have the problem anymore. 
Works like a charm ! 

`- Installing dmachard/http-client v0.3.0...
- Installed dmachard/http-client v0.3.0 (self-signed, key ID 0813FE87506B3ED4)`

Thanks a lot for your help
